/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2main;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import com.toedter.calendar.JDateChooser;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author yildi
 */
public class DoktorGirisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form DoktorGirisEkrani
     */
    static Doktor d;

    public DoktorGirisEkrani(Doktor d) {
        initComponents();
        this.d = d;
        jLabel1.setText(d.getAd() + " " + d.getSoyad());

        String bolum = d.getDoktorDepartman();

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/deneme", "root", "Melike4434@");
            Statement s = c.createStatement();
            String sorgu = "SELECT  hasta_TC FROM deneme.randevu_durumu WHERE bolum_adi = ?";
            PreparedStatement ps = c.prepareStatement(sorgu);
            ps.setString(1, bolum);
            ResultSet rs = ps.executeQuery();
            jComboBox1.removeAllItems();
            jComboBox2.removeAllItems();
            jComboBox4.removeAllItems();
            while (rs.next()) {
                String hasta_tc = rs.getString("hasta_TC");
                jComboBox1.addItem(hasta_tc);
                jComboBox2.addItem(hasta_tc);
                jComboBox4.addItem(hasta_tc);

            }
            // Kaynakları kapatma
            rs.close();
            ps.close();
            c.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        list1 = new java.awt.List();
        jButton2 = new javax.swing.JButton();
        list2 = new java.awt.List();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("          HOŞGELDİNİZ");

        jLabel1.setText("doktoradısoyadı");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("randevuları görüntüle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Randevuları görüntüle", jPanel2);

        jLabel3.setText("Detaylarını görüntülemek istediğiniz hastayı seçin:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        jButton2.setText("GÖRÜNTÜLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        list2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("KİŞİSEL BİLGİLERİ");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("TAHLİL SONUÇLARI");

        jButton3.setText("GÖRÜNTÜLE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 131, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hasta detayları görüntüle", jPanel3);

        jLabel6.setText("Hastanızı seçiniz:");

        jLabel7.setText("Tahlil türünüzü seçiniz:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kan tahlili", "İdrar tahlili", "Alerji testi", "Biopsi", "Röntgen", "Tomografi", "MR", "Hormon testi", "DNA analizi" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Tahlil sonucunu giriniz:");

        jCheckBox1.setText("Tahlil isteğinin tarafımca yapıldığını onaylıyorum");

        jButton4.setText("Oluştur");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, 0, 182, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, 182, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(78, 78, 78))
            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jButton4))
        );

        jTabbedPane1.addTab("Tahlil gir", jPanel4);

        jLabel9.setText("Hastanızı seçiniz:");

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jButton5.setText("Taburcu edin");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jButton5)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton5)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hasta taburcu", jPanel5);

        jButton8.setText("ÇIKIŞ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton8)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Doktorun bölümünü alır
        String bolum = d.getDoktorDepartman();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/deneme", "root", "Melike4434@");
            Statement s = c.createStatement();
            String sorgu = "SELECT * FROM deneme.randevu_durumu WHERE bolum_adi=?";
            PreparedStatement ps = c.prepareStatement(sorgu);
            ps.setString(1, bolum);
            ResultSet resultSet = ps.executeQuery();
            
            // Sonuçların meta verilerini alır (sütun isimleri ve sayısı)
            ResultSetMetaData metaData = resultSet.getMetaData();
            int sütunSayısı = metaData.getColumnCount();
             // JTable için model oluşturur
            DefaultTableModel model = new DefaultTableModel();
            // Sütun isimlerini modele ekler
            for (int i = 1; i <= sütunSayısı; i++) {
                model.addColumn(metaData.getColumnName(i));

            }
            // Sonuçları satır satır okur ve modele ekler
            while (resultSet.next()) {
                Object[] row = new Object[sütunSayısı];
                for (int i = 1; i <= sütunSayısı; i++) {
                    row[i - 1] = resultSet.getObject(i);
                }
                model.addRow(row);
            }
             // JTable'a modeli set eder
            jTable1.setModel(model);
            resultSet.close();
            s.close();
            c.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_list1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Doktorun bölümünü alır ve ComboBox'tan seçilen hasta TC numarasını alır
        String bolum = d.getDoktorDepartman();
        String hasta_tc = jComboBox1.getSelectedItem().toString();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/deneme", "root", "Melike4434@");
            Statement s = c.createStatement();
            String sorgu = "SELECT*FROM deneme.randevu_durumu WHERE bolum_adi=? AND hasta_TC=?";
            PreparedStatement ps = c.prepareStatement(sorgu);
            ps.setString(1, bolum);
            ps.setString(2, hasta_tc);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String sorgu2 = "SELECT*FROM deneme.hasta_bilgileri WHERE hasta_TC=?";
                PreparedStatement ps2 = c.prepareStatement(sorgu2);
                ps2.setString(1, hasta_tc);
                ResultSet rs2 = ps2.executeQuery();
                if (rs2.next()) {
                    String hasta_ad = rs2.getString("hasta_ad");
                    String hasta_soyad = rs2.getString("hasta_soyad");
                    String dg = rs2.getString("hasta_dogumTarihi");
                    String cinsiyet = rs2.getString("hasta_cinsiyet");
                    String hasta_kangrubu = rs2.getString("hasta_kanGrubu");
                    // Listeyi temizler ve yeni hasta bilgilerini ekler
                    list1.removeAll();
                    list1.add(hasta_tc, 1);
                    list1.add("\n", 2);
                    list1.add(hasta_ad, 3);
                    list1.add("\n", 4);
                    list1.add(hasta_soyad, 5);
                    list1.add("\n", 6);
                    list1.add(dg, 7);
                    list1.add("\n", 8);
                    list1.add(cinsiyet, 9);
                    list1.add("\n", 10);
                    list1.add(hasta_kangrubu, 11);
                    list1.add("\n", 12);

                }
            }
        } catch (SQLException e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String bolum = d.getDoktorDepartman();
        String hasta_tc = jComboBox1.getSelectedItem().toString();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/deneme", "root", "Melike4434@");
            Statement s = c.createStatement();
            String sorgu = "SELECT*FROM deneme.randevu_durumu WHERE bolum_adi=? AND hasta_TC=?";
            PreparedStatement ps = c.prepareStatement(sorgu);
            ps.setString(1, bolum);
            ps.setString(2, hasta_tc);
            ResultSet rs = ps.executeQuery();
            boolean found = false;
            while (rs.next()) {
                String sorgu2 = "SELECT*FROM deneme.tahlil WHERE hasta_TC=?";
                PreparedStatement ps2 = c.prepareStatement(sorgu2);
                ps2.setString(1, hasta_tc);
                ResultSet rs2 = ps2.executeQuery();
                while (rs2.next()) {
                    found = true;
                    String tahlil_adi = rs2.getString("tahlil_tipi");
                    String sonuc = rs2.getString("tahlil_sonucu");
                    // Tahlil adı ve sonuçları null değilse, listeye ekler
                    if (tahlil_adi != null && sonuc != null) {
                        list2.removeAll();
                        list2.add(tahlil_adi, 1);
                        list2.add("\n", 2);
                        list2.add(sonuc, 3);
                    }
                }
            }
            // Eğer tahlil bulunamadıysa
            if (!found) { // Eğer tahlil bulunamadıysa
                JOptionPane.showMessageDialog(this, "Hastanın herhangi bir tahlili bulunmamaktadır.");
            }
        } catch (SQLException e) {
            e.printStackTrace();

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
        String hasta_tc = jComboBox2.getSelectedItem().toString();
        String tahlil_adi = jComboBox3.getSelectedItem().toString();
        String sonuc = jTextField1.getText();
        String sorgu = "SELECT*FROM deneme.hasta_bilgileri WHERE hasta_TC=?";
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/deneme", "root", "Melike4434@");
            Statement s = c.createStatement();
            // Kullanıcının tahlil onay kutusunu işaretleyip işaretlemediğini kontrol eder
            try {
                if (!jCheckBox1.isSelected()) {
                    throw new Exception("Lütfen tahlilin tarafınızca yapıldığına onay veriniz.");

                }
            } catch (Exception e) {
                // Kullanıcıya hata mesajı gösterir ve işlemi sonlandırır
                JOptionPane.showMessageDialog(this, e.getMessage(), "UYARI", JOptionPane.ERROR_MESSAGE);
                return;
            }
            PreparedStatement ps = c.prepareStatement(sorgu);
            ps.setString(1, hasta_tc);
            ResultSet rs = ps.executeQuery();
             // Hasta bilgileri bulunursa tahlil bilgilerini veritabanına ekler
            if (rs.next()) {
                String hasta_ad = rs.getString("hasta_ad");
                String hasta_soyad = rs.getString("hasta_soyad");
                 // Tahlil bilgilerini eklemek için SQL sorgusunu hazırlar
                String olustur = "INSERT INTO deneme.tahlil(hasta_TC,hasta_ad,hasta_soyad,tahlil_tipi,tahlil_sonucu) VALUES (?,?,?,?,?)";
                PreparedStatement ps2 = c.prepareStatement(olustur);
                ps2.setString(1, hasta_tc);
                ps2.setString(2, hasta_ad);
                ps2.setString(3, hasta_soyad);
                ps2.setString(4, tahlil_adi);
                ps2.setString(5, sonuc);
                ps2.executeUpdate();
                 
                // Tahlil sonuçlarını dosyaya kaydetmek için dosya yolu belirler
                //String filePath = "C:\\Users\\yildi\\OneDrive\\Masaüstü\\projem\\proje_tahlil.txt";
                String filePath = "C:\\Users\\yildi\\OneDrive\\Masaüstü\\proje_tahlil.txt";
                try (PrintWriter writer = new PrintWriter(new FileWriter(filePath, true))) {
                    writer.println(hasta_tc + " kimlik numaralı  " + hasta_ad + "  " + hasta_soyad + " isimli kişinin tahlil bilgileri: " + tahlil_adi + " : " + sonuc + " sonuçlu tahliliniz eklenmiştir.");
                    JOptionPane.showMessageDialog(null, "Tahlil sonuçları kaydedildi.");

                } catch (IOException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Dosya yazma hatası. ");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void list2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list2ActionPerformed
        // TODO add your handling code here:
        String hasta_tc = jComboBox2.getSelectedItem().toString();
        String tahlil_adi = jComboBox3.getSelectedItem().toString();
        String sonuc = jTextField1.getText();
        String sorgu = "SELECT*FROM deneme.hasta_bilgileri WHERE hasta_TC=?";
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/deneme", "root", "Melike4434@");
            Statement s = c.createStatement();
            PreparedStatement ps = c.prepareStatement(sorgu);
            ps.setString(1, hasta_tc);
            ResultSet rs = ps.executeQuery();
             // Hasta bilgileri bulunursa dosya okuma işlemi başlar
            if (rs.next()) {
                String filePath = "C:\\Users\\yildi\\OneDrive\\Masaüstü\\projem\\proje_tahlil.txt";
                try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        String[] data = line.split(",");
                        if (data.length >= 4) {

                        } else {
                            System.out.println("Eksik veri: " + line);

                        }
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DoktorGirisEkrani.class
                            .getName()).log(Level.SEVERE, null, ex);

                } catch (IOException ex) {
                    Logger.getLogger(DoktorGirisEkrani.class
                            .getName()).log(Level.SEVERE, null, ex);

                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(DoktorGirisEkrani.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_list2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String secilen_hasta = jComboBox4.getSelectedItem().toString();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/deneme", "root", "Melike4434@");
                // Hasta bilgilerini silmek için SQL sorgusunu hazırlar

            String sil = "DELETE FROM hasta_bilgileri WHERE hasta_TC = ?";
            PreparedStatement ps = c.prepareStatement(sil);
            ps.setString(1, secilen_hasta);
            int affectedRows = ps.executeUpdate();
            
            // Randevu durumu tablosundan silmek için SQL sorgusunu hazırlar
            String silRandevuDurumu = "DELETE FROM randevu_durumu WHERE hasta_TC = ?";
            PreparedStatement ps2 = c.prepareStatement(silRandevuDurumu);
            ps2.setString(1, secilen_hasta);
            int affectedRows2 = ps2.executeUpdate();
            // Silme işlemlerinin başarılı olup olmadığını kontrol eder
            if (affectedRows > 0 && affectedRows2 > 0) {
                JOptionPane.showMessageDialog(this, "Hasta taburcu edilmiştir");
            } else {
                JOptionPane.showMessageDialog(this, "Hasta taburcu edilememiştir");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DoktorGirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }

 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorGirisEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorGirisEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorGirisEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorGirisEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoktorGirisEkrani(d).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private java.awt.List list1;
    private java.awt.List list2;
    // End of variables declaration//GEN-END:variables
}
