/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje2main;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author yildi
 */
public class NewJFrame extends javax.swing.JFrame {

    Connection c;
    ResultSet resultSet;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        //Veri tabanı bağlantısı oluşturuldu
        try {
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/deneme", "root", "Melike4434@");
            // SQL sorgusu oluştur ve çalıştır
            Statement s = c.createStatement();
            String query = "SELECT*FROM deneme.hasta_bilgileri";
            resultSet = s.executeQuery(query);

        } catch (SQLException ex) {
             // Hata durumunda loglama
            Logger.getLogger(Proje2main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldGirisHastaTC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonHastaGiris = new javax.swing.JButton();
        jButtonHastaKayıt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldHastaGiris = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldGirisDoktorTC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonDoktorGiris = new javax.swing.JButton();
        jPasswordFieldDoktorGiris = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("        YILDIZ HASTANESİ YÖNETİM SİSTEMİ");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("TC KİMLİK NUMARASI:");

        jTextFieldGirisHastaTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGirisHastaTCActionPerformed(evt);
            }
        });

        jLabel3.setText("ŞİFRE:");

        jButtonHastaGiris.setText("GİRİŞ YAP");
        jButtonHastaGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHastaGirisActionPerformed(evt);
            }
        });

        jButtonHastaKayıt.setText("KAYIT OL");
        jButtonHastaKayıt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHastaKayıtActionPerformed(evt);
            }
        });

        jLabel4.setText("ÜYE DEĞİLSENİZ KAYIT OLUNUZ");

        jPasswordFieldHastaGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldHastaGirisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldGirisHastaTC)
                    .addComponent(jPasswordFieldHastaGiris))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonHastaGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonHastaKayıt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldGirisHastaTC)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldHastaGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButtonHastaGiris)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHastaKayıt)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HASTA GİRİŞİ ", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("TC KİMLİK NUMARASI:");

        jLabel6.setText("ŞİFRE");

        jButtonDoktorGiris.setText(" GİRİŞ YAP");
        jButtonDoktorGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoktorGirisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldGirisDoktorTC)
                    .addComponent(jPasswordFieldDoktorGiris))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButtonDoktorGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGirisDoktorTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldDoktorGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButtonDoktorGiris)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DOKTOR GİRİŞİ", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jMenu1.setText("HAKKIMIZDA");

        jMenuItem2.setText("ADRES BİLGİSİ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("BAŞHEKİM");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("BİLGİLENDİRME");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("İLETİŞİM");

        jMenuItem3.setText("TELEFON ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGirisHastaTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGirisHastaTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGirisHastaTCActionPerformed

    private void jButtonHastaGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHastaGirisActionPerformed
        // TODO add your handling code here:
        // giriş ekranında boş bilgiyle giriş yapılıp yapılmadığını test eder
        if (jTextFieldGirisHastaTC.getText().length() == 0 || jPasswordFieldHastaGiris.getText().length() == 0) {

            JOptionPane.showMessageDialog(this, "Lütfen tüm boş alanları doldurunuz", "hata", JOptionPane.ERROR_MESSAGE);
        }
         // Giriş bilgilerini alır
        String hastaTC = jTextFieldGirisHastaTC.getText();
        char[] sifreKelime = jPasswordFieldHastaGiris.getPassword();
        String sifre = String.valueOf(sifreKelime);

        try {
            //Veri tabanı sorgusu için sql bağlantısı alındı
            String sorgu = "SELECT*FROM deneme.hasta_bilgileri WHERE hasta_TC=? AND hasta_sifre=?";
            PreparedStatement ps = c.prepareStatement(sorgu);
            ps.setString(1, hastaTC);
            ps.setString(2, sifre);
            //Sorguyu çalıştırır ve sonuçları alır
            resultSet = ps.executeQuery();
             
        // Eğer sonuçlar mevcutsa, kullanıcı bilgilerini alır ve yeni ekranı açar
            if (resultSet.next()) {
                String isim = resultSet.getString("hasta_ad");
                String soyad = resultSet.getString("hasta_soyad");
                Date dogum_tarihi = resultSet.getDate("hasta_dogumTarihi");
                String kan_grubu = resultSet.getString("hasta_kanGrubu");
                String cinsiyet = resultSet.getString("hasta_cinsiyet");
                // Hasta nesnesi oluşturur ve HastaGirisEkrani açar
                Hasta h = new Hasta(isim, soyad, sifre, hastaTC,dogum_tarihi,kan_grubu,cinsiyet);
                new HastaGirisEkrani(h).setVisible(true);
                dispose();
            } else {
                // Eğer sonuçlar mevcut değilse, hata fırlatır
                throw new Exception("Hatalı bilgi girişi yapıldı ,tekrar deneyiniz");

            }
        } catch (SQLException ex) {
             // SQL hatalarını loglar
            Logger.getLogger(Proje2main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            // Diğer hataları gösterir ve loglar
            JOptionPane.showMessageDialog(this, ex, "hata", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonHastaGirisActionPerformed

    private void jPasswordFieldHastaGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldHastaGirisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldHastaGirisActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        JOptionPane.showMessageDialog(this, "ADRES:Bağdat caddesi ,kirazlı sokak No:3 \n Kadıköy/İstanbul", "adres", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Başhekimimiz Sayın Rabia SEZEN.\n Ana dalı Kadın doğum olan Rabia hanım 2013 Yılında Cerrahpaşa Tıp Fakültesinden mezun olmuştur", "bilgilendirme", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "0212 856 56 56 \n 0212 654 54 54 ", "iletişim numaraları", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonHastaKayıtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHastaKayıtActionPerformed
        // TODO add your handling code here:
        new HastaKayitEkrani().setVisible(true);
    }//GEN-LAST:event_jButtonHastaKayıtActionPerformed

    private void jButtonDoktorGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoktorGirisActionPerformed
        // TODO add your handling code here:
        // giriş için girilen değerlerin boş olup olmadığını kontrol eder.
        if(jTextFieldGirisDoktorTC.getText().length()==0 && jPasswordFieldDoktorGiris.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Lütfen bilgilerinizi eksiksiz girdiğinizden emin olun.");
        }
        String doktorTC = jTextFieldGirisDoktorTC.getText();
        char[] sifreKelime = jPasswordFieldDoktorGiris.getPassword();
        String sifre = String.valueOf(sifreKelime);

        try {
            //Veri tabanı sorgusu oluşturur
            String sorgu = "SELECT*FROM deneme.doktor_bilgileri WHERE doktor_TC=? AND doktor_sifre=?";
            PreparedStatement ps = c.prepareStatement(sorgu);
            ps.setString(1, doktorTC);
            ps.setString(2, sifre);
            //Sorguyu çalıştırır ve sonuçları alır
            resultSet = ps.executeQuery();
            
            // Sonuçlar mevcutsa kullanıcının bilgilerini alır ve yeni ekrana gider.
            if (resultSet.next()) {
                String isim = resultSet.getString("doktor_adi");
                String soyad = resultSet.getString("doktor_soyadi");
                String departman=resultSet.getString("doktor_departman");
                Doktor d=new Doktor(isim,soyad,sifre,doktorTC,departman);
                 
                new DoktorGirisEkrani(d).setVisible(true);
                dispose();
            } else {
                throw new Exception("Hatalı bilgi girişi yapıldı ,tekrar deneyiniz");

            }
        } catch (SQLException ex) {
            Logger.getLogger(Proje2main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "hata", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonDoktorGirisActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Sizlere daha iyi hizmet verebilmek için hastanemizde sadece belirli bölümler bulunmaktadır ve her bölüm için birer doktorumuz vardır , anlayışınız için teşekkürlere. ","MESAJ",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDoktorGiris;
    private javax.swing.JButton jButtonHastaGiris;
    private javax.swing.JButton jButtonHastaKayıt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldDoktorGiris;
    private javax.swing.JPasswordField jPasswordFieldHastaGiris;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldGirisDoktorTC;
    private javax.swing.JTextField jTextFieldGirisHastaTC;
    // End of variables declaration//GEN-END:variables
}
